use_default_settings: true

general:
  instance_name: "DDEV SearXNG"

server:
  secret_key: "ddev-searxng-local-secret"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  formats:
    - html
    - json
